version: '3.8'
services:
    # --- СЕРВИС БАЗЫ ДАННЫХ ---
    wms-db:
        image: postgres:16-alpine
        container_name: wms_postgres_db
        environment:
            POSTGRES_DB: wms_db
            POSTGRES_USER: wms_admin
            POSTGRES_PASSWORD: super_secret_password_2026
        ports:
            - "5432:5432"
        volumes:
            # Сохраняем данные базы на жестком диске сервера
            - pgdata:/var/lib/postgresql/data
        # проверять работоспособность базы данны
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "wms_db", "-U", "wms_admin"]
            timeout: 5s
            retries: 5
            start_period: 10s
        networks:
            - wms-network

    # --- СЕРВИС SPRING BOOT БЭКЕНДА ---
    wms-spring:
        build: .
        container_name: wms_spring
        ports:
            - "5000:5000"
        environment:
            # Связываем Spring Boot с базой данных внутри сети Docker по имени контейнера
            SPRING_DATASOURCE_URL: jdbc:postgresql://wms-db:5432/wms_db
            SPRING_DATASOURCE_USERNAME: wms_admin
            SPRING_DATASOURCE_PASSWORD: super_secret_password_2026
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
        volumes:
            - .:/var/www/wms/backend/api:rw
        depends_on:
            wms-db:
                condition: service_healthy
        networks:
            - wms-network

volumes:
    pgdata:

networks:
    wms-network:
        driver: bridge